config/routes.rb
Rails.application.routes.draw do
  resources :mountains do
    collection do
      post :import
    end
  end

  delete :clear_mountains, to: "mountains#clear"

  root 'pages#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/mountain.rb
class Mountain < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mountains_controller.rb
class MountainsController < ApplicationController
  before_action :set_mountain, only: %i[ show edit update destroy ]

  def import
    file = params[:file]

    # Redirect if bad data
    return redirect_to root_path, alert: 'No file selected.' unless file
    return redirect_to root_path, alert: 'Please select CSV file instead.' unless file.content_type == 'text/csv'
    
    # Import data
    csvImportService = CSVImportService.new(file)
    csvImportService.import

    # Redirect with notice
    redirect_to root_path, notice: "#{csvImportService.number_imported_with_last_run} mountains were imported."
  end

  def clear
    Mountain.destroy_all
    redirect_to root_path, notice: "All mountains cleared."
  end

  # GET /mountains or /mountains.json
  def index
    @mountains = Mountain.all
  end

  # GET /mountains/1 or /mountains/1.json
  def show
  end

  # GET /mountains/new
  def new
    @mountain = Mountain.new
  end

  # GET /mountains/1/edit
  def edit
  end

  # POST /mountains or /mountains.json
  def create
    @mountain = Mountain.new(mountain_params)

    respond_to do |format|
      if @mountain.save
        format.html { redirect_to mountain_url(@mountain), notice: "Mountain was successfully created." }
        format.json { render :show, status: :created, location: @mountain }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mountain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mountains/1 or /mountains/1.json
  def update
    respond_to do |format|
      if @mountain.update(mountain_params)
        format.html { redirect_to mountain_url(@mountain), notice: "Mountain was successfully updated." }
        format.json { render :show, status: :ok, location: @mountain }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mountain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mountains/1 or /mountains/1.json
  def destroy
    @mountain.destroy

    respond_to do |format|
      format.html { redirect_to mountains_url, notice: "Mountain was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mountain
      @mountain = Mountain.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mountain_params
      params.require(:mountain).permit(:name, :height)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include MountainsHelper
  def home
    @mountains = Mountain.all
    @chart_data = counts_by_difficulty(Mountain)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mountains_helper.rb
module MountainsHelper
  def counts_by_difficulty(mountains)
    groups = categorize_by_height(mountains).count
    order_by_category(groups)
  end

  private
  def categorize_by_height(mountains)
    mountains.group("case 
      when height <800 then 'low' 
      when height >=800 and height <1100 then 'medium'
      when height >=1100 then 'high'
    end")
  end

  def order_by_category(groups)
    groups.sort_by do |k,v|
      case k
      when "low" then 1
      when "medium" then 2
      when "high" then 3
      end
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_alerts.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MountainsImporter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "layouts/alerts" %>
    <div class="container mt-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/mountains/_form.html.erb
<%= form_with(model: mountain) do |form| %>
  <% if mountain.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mountain.errors.count, "error") %> prohibited this mountain from being saved:</h2>

      <ul>
        <% mountain.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :height, style: "display: block" %>
    <%= form.text_field :height %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/mountains/_import_form.html.erb
<%= form_with url: import_mountains_path, method: :post do |f| %>
  <div class="container">
    <div class="d-flex justify-content-end">
      <%= f.file_field :file, accept: ".csv" %>
      <div class="btn-group">
        <%= f.submit "Upload Mountains", class: "btn btn-primary" %>
        <%= link_to "Clear Mountains", clear_mountains_path, class: "btn btn-danger", 
        data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?"
        } %>
      </div>
    </div>
  </div>
<% end %>

app/views/mountains/_mountain.html.erb
<div id="<%= dom_id mountain %>">
  <p>
    <strong>Name:</strong>
    <%= mountain.name %>
  </p>

  <p>
    <strong>Height:</strong>
    <%= mountain.height %>
  </p>

</div>

app/views/mountains/edit.html.erb
<h1>Editing mountain</h1>

<%= render "form", mountain: @mountain %>

<br>

<div>
  <%= link_to "Show this mountain", @mountain %> |
  <%= link_to "Back to mountains", mountains_path %>
</div>

app/views/mountains/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Mountains</h1>

<div id="mountains">
  <% @mountains.each do |mountain| %>
    <%= render mountain %>
    <p>
      <%= link_to "Show this mountain", mountain %>
    </p>
  <% end %>
</div>

<%= link_to "New mountain", new_mountain_path %>

app/views/mountains/new.html.erb
<h1>New mountain</h1>

<%= render "form", mountain: @mountain %>

<br>

<div>
  <%= link_to "Back to mountains", mountains_path %>
</div>

app/views/mountains/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @mountain %>

<div>
  <%= link_to "Edit this mountain", edit_mountain_path(@mountain) %> |
  <%= link_to "Back to mountains", mountains_path %>

  <%= button_to "Destroy this mountain", @mountain, method: :delete %>
</div>

app/views/pages/home.html.erb
<h1>Mountains Importer™</h1>
<p>Let's import some mountains.</p>

<%= render "mountains/import_form" %>
<%# column_chart Mountain.group("SUBSTR(name, 1, 1)").count, xtitle: "Elevation (m)" %>
<%= column_chart @chart_data, 
  xtitle: "Difficulty Based on Elevation", 
  ytitle: "Number of Mountains",
  order: ["low", "medium", "high"]
%>
<% @mountains.each do |mountain| %>
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= mountain.name %></h5>
      <h6 class="card-subtitle mb-2 text-muted"><%= mountain.height %></h6>
    </div>
  </div>
<% end %>